"""
Django settings for Video Editing Agent project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True so local/dev setups without the var keep working unchanged;
# the prod .env sets DJANGO_DEBUG=false explicitly (same opt-out pattern as CHAT_ENABLED below).
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

# Comma-separated host/domain list read from env — empty by default, which is fine
# while DEBUG=True (Django auto-allows localhost/127.0.0.1 in that mode); prod .env
# sets DJANGO_ALLOWED_HOSTS=sherazlabs.co.uk since DEBUG=False requires this to be non-empty.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]

# Django checks the request's Origin header against this for unsafe (POST/PUT/etc.)
# requests — needed in addition to ALLOWED_HOSTS once the site is served over HTTPS.
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS]

# nginx terminates TLS and proxies to gunicorn over plain HTTP, so Django can't tell
# the request was HTTPS from the connection itself — it trusts nginx's
# X-Forwarded-Proto header instead. Only safe because nginx (not the client) sets it.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Redirect/secure-cookie settings only make sense once TLS is actually in front of the
# app (prod, behind nginx) — leave them off in DEBUG/local dev where there's no HTTPS.
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Starts at one week rather than the commonly-recommended one year — HSTS is a
# browser-enforced, hard-to-undo commitment to HTTPS for the domain; a short window
# limits the damage if the cert/proxy setup turns out to have a problem after deploy.
SECURE_HSTS_SECONDS = 0 if DEBUG else 60 * 60 * 24 * 7
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = False  # preload registration is effectively irreversible; opt in later once confident


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Required: shared core library (template tags + design system)
    'dj_control_room_base',

    # Add any panels you installed
    'dj_redis_panel',
    'dj_cache_panel',
    'dj_urls_panel',
    "dj_signals_panel",
    "dj_celery_panel",

    # Then add Django Control Room
    'dj_control_room',
    'pipeline',
    'videos',
    'chat',
    'user_accounts',  # user profiles and subscription plans
    'portfolio',  # public personal homepage (and later /about, case studies)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Must run after AuthenticationMiddleware (needs request.user resolved) — gives
    # anonymous visitors a stable guest_id so they can own VideoJobs without an account.
    'videos.middleware.GuestIdentityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'video_editing_agent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user_accounts.context_processors.user_plan',  # injects user_plan into every template
                'videos.context_processors.guest_identity',  # injects guest_id into every template
            ],
        },
    },
]

WSGI_APPLICATION = 'video_editing_agent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # Postgres instead of sqlite3 so concurrent agent tool-call writes
        # (LLMCall rows, session/job token totals) don't serialize behind
        # sqlite's single whole-file write lock. Connects to the `db`
        # service in docker-compose.yml by default; override POSTGRES_HOST
        # to point elsewhere.
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'video_editing_agent'),
        'USER': os.environ.get('POSTGRES_USER', 'video_editing_agent'),
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Destination for `collectstatic` — nginx serves straight from this directory in prod
# (Django itself stops serving static files once DEBUG=False). Unused locally since
# runserver serves STATICFILES_DIRS directly without needing collectstatic.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect to upload page after login/logout (the app's natural home screen)
# '/' is now the public SherazLabs homepage (Version 2), not the app — send a
# signed-in user straight into the app instead of dropping them back on marketing copy.
LOGIN_REDIRECT_URL = '/upload/'
LOGOUT_REDIRECT_URL = '/'

# Global emergency off-switch for the AI chat feature (e.g. cost spike, abuse wave).
# Set CHAT_ENABLED=false in .env to disable chat app-wide without a code deploy;
# defaults to enabled so local/dev setups without the var keep working.
CHAT_ENABLED = os.environ.get('CHAT_ENABLED', 'true').lower() != 'false'

# Hard cap on a single chat message's length (characters). Blocks someone from
# pasting a huge wall of text and burning a large chunk of token budget in one
# turn, independent of how much history the session has already built up.
CHAT_MAX_MESSAGE_CHARS = int(os.environ.get('CHAT_MAX_MESSAGE_CHARS', 8000))

# Cumulative token budget (prompt + completion, summed across every LLMCall)
# for a single chat session. History is resent on every turn, so cost compounds
# turn-over-turn even with small messages; once a session crosses this, it's
# locked (ChatSession.is_over_budget) and the user must start a New Chat.
CHAT_SESSION_TOKEN_BUDGET = int(os.environ.get('CHAT_SESSION_TOKEN_BUDGET', 150000))

# --- Guest access ---
# Anonymous visitors get a random per-browser identity (GuestIdentityMiddleware)
# instead of an account, so they can upload/process a video without signing up.
# Name of the cookie that carries a guest's identity (VideoJob.guest_id).
GUEST_ID_COOKIE_NAME = 'guest_id'
# These values are promised to visitors in the privacy notice
# (portfolio/templates/portfolio/privacy.html, section 7) — change both together.
# How long a guest's uploaded video/output files survive before purge_guest_jobs
# deletes just the files and marks the job Status.EXPIRED (row + chat kept).
GUEST_VIDEO_TTL_HOURS = 6
# How long the whole VideoJob row (and its chat history) survives before
# purge_guest_jobs deletes it entirely — longer than the video TTL so a guest's
# chat/audit trail outlives the video itself, similar to how e.g. Gemini's
# incognito chats are described as temporary but not instantly gone.
GUEST_CHAT_TTL_HOURS = 30 * 24  # 30 days
# Cookie needs to live at least as long as GUEST_CHAT_TTL_HOURS — otherwise a guest
# loses access to their still-existing chat history once the cookie expires first.
GUEST_ID_COOKIE_MAX_AGE = GUEST_CHAT_TTL_HOURS * 60 * 60
# Both TTLs above need purge_guest_jobs to actually run on a schedule (cron /
# Windows Task Scheduler) in any real deployment — it does nothing on its own.
# Cap on how many not-yet-purged jobs one guest identity can have open at once.
# Guests have no account to rate-limit against, so this bounds per-browser storage
# and (since guests get chat/agent access) LLM cost.
GUEST_MAX_OPEN_JOBS = 3
# After this many days purge_guest_jobs anonymises GuestIntake and GuestFeedback
# rows instead of deleting them: guest id, free-text answers and the job link are
# removed and the date is cut to the month, so the rest can be kept for
# year-on-year trends (anonymous data falls outside UK GDPR's storage limit).
GUEST_ANONYMISE_AFTER_DAYS = 365

# settings.py
DJ_CONTROL_ROOM_SETTINGS = {
    # Global: Show panels in both Control Room and their own sections
    'REGISTER_PANELS_IN_ADMIN': True,  # Default: False

    # Per-panel: Override for specific panels
    'PANEL_ADMIN_REGISTRATION': {
        'dj_redis_panel': True,   # Redis in both places
        'dj_cache_panel': False,  # Cache only in Control Room
    },

    # CSS: load built-in styles and/or inject your own
    'LOAD_DEFAULT_CSS': True,
    # Static paths are relative to app's static/ dir (e.g. 'myapp/css/overrides.css'
    # for a file at myapp/static/myapp/css/overrides.css). Full URLs also accepted.
    'EXTRA_CSS': [],
}