# Generated by Django 6.0.6 on 2026-06-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='uploads/')),
                ('transcript', models.JSONField(blank=True, null=True)),
                ('captions', models.JSONField(blank=True, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('stage', models.CharField(blank=True, choices=[('transcribed', 'Transcribed'), ('captioned', 'Captioned'), ('rendered', 'Rendered')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
