# Generated by Django 6.0.6 on 2026-07-03 15:01

import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_captioned_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=videos.models._asset_upload_path)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('pdf', 'Pdf')], max_length=10)),
                ('original_name', models.CharField(max_length=255)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_assets', to='videos.videojob')),
                ('source_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='videos.uploadedasset')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
