# Generated by Django 6.0.6 on 2026-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videojob_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
