# Generated by Django 6.0.6 on 2026-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_videojob_guest_id_alter_videojob_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
