# Generated by Django 6.0.6 on 2026-07-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_guestfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='total_completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videojob',
            name='total_prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
