# Generated by Django 6.0.6 on 2026-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_backfill_job_token_totals'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.UUIDField(db_index=True)),
                ('referral_source', models.CharField(max_length=255)),
                ('use_case', models.TextField()),
                ('looking_for_engineer', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
