# Generated by Django 6.0.6 on 2026-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_tool_name_alter_chatmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='completion_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='prompt_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
