# Generated by Django 6.0.6 on 2026-07-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_llmcall_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
