# Generated by Django 6.0.6 on 2026-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatsession_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_over_budget',
            field=models.BooleanField(default=False),
        ),
    ]
