# Generated by Django 6.0.6 on 2026-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatsession_is_over_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='total_completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
