# Generated by Django 6.0.6 on 2026-09-27 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('build_log', 'Build log'), ('war_story', 'War story'), ('note', 'Note')], default='build_log', max_length=20)),
                ('summary', models.CharField(max_length=300)),
                ('body', models.TextField(help_text='Markdown. Headings, lists, links, ```code blocks``` and tables work.')),
                ('is_draft', models.BooleanField(default=True, help_text='Untick to publish.')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medium_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
