from django.conf import settings
from django.db import models


def _asset_upload_path(instance, filename):
    # Namespaced by job id so uploads from different jobs never collide on disk.
    return f'asset_uploads/{instance.job_id}/{filename}'


class VideoJob(models.Model):
    class Status(models.TextChoices):
        PENDING = 'pending'
        PROCESSING = 'processing'
        DONE = 'done'
        FAILED = 'failed'

    class Stage(models.TextChoices):
        TRANSCRIBED = 'transcribed'
        CAPTIONED = 'captioned'
        RENDERED = 'rendered'

    # Owning user — every view must filter/lookup by (pk, owner) so one account
    # can never read, edit, or delete another account's job by guessing an id.
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='video_jobs')
    input_file = models.FileField(upload_to='uploads/')
    transcript = models.JSONField(null=True, blank=True)
    assets = models.JSONField(null=True, blank=True)
    output_file = models.FileField(upload_to='outputs/', null=True, blank=True)
    stage = models.CharField(max_length=20, choices=Stage.choices, null=True, blank=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)
    error_message = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']


class UploadedAsset(models.Model):
    # A file the user uploaded from the Assets panel — an image directly, or an
    # image rasterized from one page of an uploaded PDF (see source_pdf below).
    # Kept as its own model (not folded into VideoJob.assets) because assets is a
    # JSONField and can't hold binary file data.
    class Kind(models.TextChoices):
        IMAGE = 'image'
        PDF = 'pdf'

    job = models.ForeignKey(VideoJob, on_delete=models.CASCADE, related_name='uploaded_assets')
    file = models.FileField(upload_to=_asset_upload_path)
    kind = models.CharField(max_length=10, choices=Kind.choices)
    original_name = models.CharField(max_length=255)
    # Set only on images generated by rasterizing a PDF page; links back to that
    # PDF's own row so the Assets panel/agent can show which file a page came from.
    source_pdf = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='pages')
    page_number = models.PositiveIntegerField(null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['uploaded_at']
